# Generated by Django 5.2.1 on 2025-05-14 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('access', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20)),
                ('auto_join', models.BooleanField(default=False)),
                ('accept_member', models.BooleanField(default=True)),
                ('accept_data', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': '2. Projects',
                'db_table': 'ad_projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(blank=True, max_length=10, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.IntegerField(null=True, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('xlsform', models.FileField(blank=True, null=True, upload_to='jform/defn/')),
                ('form_actions', models.CharField(blank=True, max_length=255, null=True)),
                ('form_defn', models.TextField(blank=True, null=True)),
                ('children', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_updated_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='projects.project')),
            ],
            options={
                'verbose_name': 'Form definition',
                'verbose_name_plural': '4. Form Definitions',
                'db_table': 'ad_form_definitions',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': '3. Project Members',
                'db_table': 'ad_project_members',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': '1. Tags',
                'db_table': 'ad_tags',
                'managed': True,
                'indexes': [models.Index(fields=['title'], name='ad_tags_title_f5c954_idx')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='projects.tag'),
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(blank=True, max_length=100, null=True)),
                ('original_uuid', models.TextField(blank=True, max_length=100, null=True)),
                ('parent_id', models.TextField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('gps', models.CharField(blank=True, max_length=150, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('form_data', models.JSONField()),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_name', models.TextField(blank=True, null=True)),
                ('synced', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fd_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fd_updated_by', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='projects.formdefinition')),
            ],
            options={
                'verbose_name': 'Form data',
                'verbose_name_plural': '5. Form data',
                'db_table': 'ad_form_data',
                'indexes': [models.Index(fields=['uuid', 'form', 'created_at'], name='ad_form_dat_uuid_2be738_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='formdefinition',
            index=models.Index(fields=['title', 'code', 'short_title'], name='ad_form_def_title_2bef48_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'member'], name='ad_project__project_d60c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title', 'code'], name='ad_projects_title_bd653a_idx'),
        ),
    ]
