@hostname = https://fao.afyadata.sacids.org/api/v1/
@hostname = https://fao.afyadata.sacids.org/api/v1/
//@hostname = http://127.0.0.1:8000/api/v1/
@login_url = {{hostname}}token/
@form_definition_url = {{hostname}}/api/v2/form-defn/


@accesstoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwODk0OTY5LCJpYXQiOjE3NzAwMzA5NjksImp0aSI6IjNiZGE5MjJmYmY1MjQzNzQ5M2NhZjBkMTUwOWFiZmJkIiwidXNlcl9pZCI6Mzl9.qpgfuheI5JgSe77TBm-c6_Qxs2ayy4J9It9uaEAbqtg
@accesstoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwODk0OTY5LCJpYXQiOjE3NzAwMzA5NjksImp0aSI6IjNiZGE5MjJmYmY1MjQzNzQ5M2NhZjBkMTUwOWFiZmJkIiwidXNlcl9pZCI6Mzl9.qpgfuheI5JgSe77TBm-c6_Qxs2ayy4J9It9uaEAbqtg
###
# Login to get access token
# @name login
POST {{login_url}}
Content-Type: application/json

{
  "username": "admin",
  "password": "21@Sacids!"
}

###
GET {{hostname}}projects
Authorization: Bearer {{login.response.body.access}}



###
# @name register
POST {{hostname}}register
Content-Type: application/json

{
  "fullName": "Job",
  "username": "0811111111",
  "password": "kitimoto",
  "passwordConfirm": "kitimoto",
  "phoneNumber": "0711111111"
}



###
# Verify token
# @name languages
GET {{hostname}}languages/
#Authorization: Bearer {{accesstoken}}
Content-Type: application/json



###
# Verify token
# @name formreactions
GET {{hostname}}form-reactions
Authorization: Bearer {{login.response.body.access}}
Content-Type: application/json




###
# Verify token
# @name submit data
POST {{hostname}}form-data
Authorization: Bearer {{login.response.body.access}}
Content-Type: application/json

{
     "id": 33,
     "project": "64c27204-7c1b-49b1-986c-a9a4c18988f2",
     "form": "c083f439-7567-45c1-9370-d7148058f153",
     "title": "ACS : : ",
     "uuid": "ea14e47f-fb54-48bc-9d9c-728b038d349d",
     "original_uuid": "ea14e47f-fb54-48bc-9d9c-728b038d349c",
     "parent_uuid": null,
     "gps": "{\"latitude\":-6.824944,\"longitude\":39.2832387,\"altitude\":-13.09999942779541,\"accuracy\":100,\"timestamp\":\"2026-04-12T12:19:56.319Z\"}",
     "deleted": 0,
     "archived": 0,
     "form_data": "{\"region\":\"morogoro\",\"district\":\"mvomero\",\"ward\":\"Bunduki\",\"village\":\"Hdb\",\"species\":\"cattle\",\"symptoms\":[\"B01\"],\"numb_of_young_show_sympt\":\"1\",\"numb_of_young_died_sympt\":\"1\",\"numb_of_adult_show_sympt\":\"1\",\"numb_of_adult_died_sympt\":\"1\",\"gps_location\":\"-6.824944 39.2832387 -13.09999942779541 100\",\"app_version\":\"2.5.5\",\"form_version\":\"20260326145913\"}",
     "created_by": 2,
     "created_by_name": "Eric",
     "created_on": "2026-04-12T12:20:01.008Z",
     "status": "finalized",
     "status_date": "2026-04-12T12:20:01.008Z",
     "synced": 0
}



###
# Verify token
# @name verify_token
POST {{hostname}}chat/conversations
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{"title":"'Dalili za Mifugo :Jesga0787878786Jomba'","form":"077e3316-67f9-483b-bdc7-550046c3a445","instance":"daff4474-376f-4ed9-b880-4c09cf0c7bdd","participants":[]}


###
# Verify token
# @name verify_token
GET {{hostname}}chat/conversations
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{"form": "077e3316-67f9-483b-bdc7-550046c3a445", "instance": undefined, "participants": [], "title": "'Dalili za Mifugo :Jesga0787878786Jomba'"}

###
# Verify token
# @name verify_token
POST {{hostname}}chat/conversations/5d99ce90-5fba-4deb-b867-2b07713492fd/messages
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{"external_id": "daff4474-376f-4ed9-b880-4c09cf0c7bd5", "text": "Moja moja"}




### Register a Project on the Central Hub
POST http://hub.afyadata.sacids.org:8000/api/v1/projects/register/
Content-Type: application/json
X-Api-Key: afyadata_Zsm1jjcSbSDCt289e8h-Ioj8QratlLC5AIbbQGSEW6w

{
    "name": "Zanzibar Malaria Surveillance",
    "description": "Testing the hub registration via VS Code",
    "instance_url": "http://127.0.0.1:8040",
    "remote_project_id": "999"
}

###

### Search for Projects (Discovery)
GET http://hub.afyadata.sacids.org:8000/api/v1/projects/discover/?search=Zanzibar
Accept: application/json